[versions]
detekt = "1.23.8"
ktlintGradle = "14.0.1"
pluginPublish = "2.0.0"
versionCheck = "0.53.0"
junit = "6.0.2"
schemaRegistryClient = "8.1.1"
kafkaSchemaSerializer = "8.1.1"
shadow = "9.3.1"
testcontainers = "2.0.3"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}
shadow = { id = "com.gradleup.shadow", version.ref = "shadow"}

[libraries]
schemaRegistryClient = { module = "io.confluent:kafka-schema-registry-client", version.ref = "schemaRegistryClient"}
kafkaSchemaSerializer = { module = "io.confluent:kafka-schema-serializer", version.ref = "kafkaSchemaSerializer"}

junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }

testcontainersBom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers"}
testcontainers = { module = "org.testcontainers:testcontainers"}
testcontainersKafka = { module = "org.testcontainers:testcontainers-kafka"}
testcontainersJunitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter"}
